-- =============================================================================
-- CUI Mod Manager Text by [eudaimonia]
-- =============================================================================

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES

-- =============================================================================
("de_DE",      "LOC_CUI_MM_MAP_CREATED",                                        "Erstellt: {1_Time: datetime}"),
("de_DE",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("de_DE",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("de_DE",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("de_DE",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("de_DE",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("de_DE",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("de_DE",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("de_DE",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("de_DE",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("de_DE",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("de_DE",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("de_DE",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("de_DE",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("de_DE",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("de_DE",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("de_DE",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("de_DE",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("de_DE",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("de_DE",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("de_DE",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("de_DE",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("de_DE",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("en_US",      "LOC_CUI_MM_MAP_CREATED",                                        "Created: {1_Time: datetime}"),
("en_US",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("en_US",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("en_US",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("en_US",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("en_US",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("en_US",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("en_US",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("en_US",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("en_US",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("en_US",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("en_US",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("en_US",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("en_US",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("en_US",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("en_US",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("en_US",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("en_US",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("en_US",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("en_US",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("en_US",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("en_US",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("en_US",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("es_ES",      "LOC_CUI_MM_MAP_CREATED",                                        "Creado: {1_Time: datetime}"),
("es_ES",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("es_ES",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("es_ES",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("es_ES",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("es_ES",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("es_ES",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("es_ES",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("es_ES",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("es_ES",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("es_ES",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("es_ES",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("es_ES",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("es_ES",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("es_ES",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("es_ES",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("es_ES",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("es_ES",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("es_ES",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("es_ES",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("es_ES",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("es_ES",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("es_ES",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("fr_FR",      "LOC_CUI_MM_MAP_CREATED",                                        "Création: {1_Time: datetime}"),
("fr_FR",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("fr_FR",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("fr_FR",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("fr_FR",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("fr_FR",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("fr_FR",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("fr_FR",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("fr_FR",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("fr_FR",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("fr_FR",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("fr_FR",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("fr_FR",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("fr_FR",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("fr_FR",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("fr_FR",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("fr_FR",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("fr_FR",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("fr_FR",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("fr_FR",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("fr_FR",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("fr_FR",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("fr_FR",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("it_IT",      "LOC_CUI_MM_MAP_CREATED",                                        "Creata: {1_Time: datetime}"),
("it_IT",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("it_IT",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("it_IT",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("it_IT",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("it_IT",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("it_IT",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("it_IT",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("it_IT",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("it_IT",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("it_IT",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("it_IT",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("it_IT",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("it_IT",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("it_IT",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("it_IT",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("it_IT",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("it_IT",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("it_IT",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("it_IT",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("it_IT",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("it_IT",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("it_IT",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("ja_JP",      "LOC_CUI_MM_MAP_CREATED",                                        "作成: {1_Time: datetime}"),
("ja_JP",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("ja_JP",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("ja_JP",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("ja_JP",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("ja_JP",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("ja_JP",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("ja_JP",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("ja_JP",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("ja_JP",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("ja_JP",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("ja_JP",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("ja_JP",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("ja_JP",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("ja_JP",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("ja_JP",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("ja_JP",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("ja_JP",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("ja_JP",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("ja_JP",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("ja_JP",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("ja_JP",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("ja_JP",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("ko_KR",      "LOC_CUI_MM_MAP_CREATED",                                        "생성됨: {1_Time: datetime}"),
("ko_KR",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("ko_KR",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("ko_KR",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("ko_KR",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("ko_KR",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("ko_KR",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("ko_KR",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("ko_KR",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("ko_KR",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("ko_KR",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("ko_KR",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("ko_KR",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("ko_KR",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("ko_KR",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("ko_KR",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("ko_KR",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("ko_KR",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("ko_KR",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("ko_KR",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("ko_KR",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("ko_KR",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("ko_KR",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("pl_PL",      "LOC_CUI_MM_MAP_CREATED",                                        "Stworzone: {1_Time: datetime}"),
("pl_PL",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("pl_PL",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("pl_PL",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("pl_PL",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("pl_PL",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("pl_PL",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("pl_PL",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("pl_PL",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("pl_PL",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("pl_PL",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("pl_PL",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("pl_PL",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("pl_PL",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("pl_PL",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("pl_PL",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("pl_PL",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("pl_PL",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("pl_PL",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("pl_PL",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("pl_PL",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("de_DE",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("de_DE",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("pt_BR",      "LOC_CUI_MM_MAP_CREATED",                                        "Criado: {1_Time: datetime}"),
("pt_BR",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("pt_BR",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("pt_BR",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("pt_BR",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("pt_BR",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("pt_BR",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("pt_BR",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("pt_BR",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("pt_BR",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("pt_BR",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("pt_BR",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("pt_BR",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("pt_BR",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("pt_BR",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("pt_BR",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("pt_BR",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("pt_BR",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("pt_BR",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("pt_BR",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("pt_BR",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("pt_BR",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("pt_BR",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("ru_RU",      "LOC_CUI_MM_MAP_CREATED",                                        "Авторы: {1_Time: datetime}"),
("ru_RU",      "LOC_CUI_MM_MODS_CONTAINS",                                      "Contains {1_total} {1_total : plural 1?Mod; other?Mods;} ({2_enabled}/{1_total})"),
("ru_RU",      "LOC_CUI_MM_MODS_BY",                                            "Mods By: {1_author}"),
("ru_RU",      "LOC_CUI_MM_UNNAMED_FOLDER",                                     "Unnamed Folder"),
("ru_RU",      "LOC_CUI_MM_UPDATED_WEEK",                                       "Updated: < 1 Week"),
("ru_RU",      "LOC_CUI_MM_UPDATED_MONTH1",                                     "Updated: < 1 Month"),
("ru_RU",      "LOC_CUI_MM_UPDATED_MONTH3",                                     "Updated: < 3 Months"),
("ru_RU",      "LOC_CUI_MM_UPDATED_MONTH6",                                     "Updated: < 6 Months"),
("ru_RU",      "LOC_CUI_MM_UPDATED_MORE",                                       "Updated: > 6 Months"),
("ru_RU",      "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "Organized By Author"),
("ru_RU",      "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "Organized By Update Time"),
("ru_RU",      "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "Organized By Enabled"),
("ru_RU",      "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "Organized By Custom Folders"),
("ru_RU",      "LOC_CUI_MM_USER_GUIDE",                                         "User Guide"),
("ru_RU",      "LOC_CUI_MM_GUIDE",                                              "Mod[NEWLINE][ICON_BULLET] Left Click: select / unselect[NEWLINE][ICON_BULLET] Right Click: enable / disable[NEWLINE][ICON_BULLET] Middle Click: close folder[NEWLINE][NEWLINE]Folder[NEWLINE][ICON_BULLET] Left Click: open / close[NEWLINE][ICON_BULLET] Right Click: enable / disable all[NEWLINE][NEWLINE][NEWLINE]Customize Folders[NEWLINE][ICON_BULLET] You can find the config file named 'CustomFolder.lua' in:[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] You can open/edit it with any text editor you have.[NEWLINE][ICON_BULLET] (Notepad++ is recommended)[NEWLINE][ICON_BULLET] Follow the instructions in the file to customize your own folders."),
("ru_RU",      "LOC_CUI_MM_GENERATE_CODE",                                      "Generate Mod ID"),
("ru_RU",      "LOC_CUI_MM_CODE_GUIDE",                                         "Append the following code to the 'CustomFolder.lua' file[NEWLINE]to add this mod to a custom folder."),
("ru_RU",      "LOC_CUI_MM_ENABLE_CONFIRM",                                     "Enable Confirm"),
("ru_RU",      "LOC_CUI_MM_ENABLE_DIALOG",                                      "This folder is depending on {1_num} {1_num : plural 1?mod; other?mods;} in other folders.[NEWLINE]Do you want to enable {1_num : plural 1?it; other?them;} too?"),
("ru_RU",      "LOC_CUI_MM_DISABLE_CONFIRM",                                    "Disable Confirm"),
("ru_RU",      "LOC_CUI_MM_DISABLE_DIALOG",                                     "Other folders have {1_num} {1_num : plural 1?mod; other?mods;} depending on this folder.[NEWLINE]Do you want to disable {1_num : plural 1?it; other?them;} too?"),
("ru_RU",      "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "Non-Steam Workshop"),
("ru_RU",      "LOC_CUI_MM_NON_STEAM_MOD",                                      "not a Steam Workshop mod"),


-- =============================================================================
("zh_Hans_CN", "LOC_CUI_MM_MAP_CREATED",                                        "创建于：{1_Time: datetime}"),
("zh_Hans_CN", "LOC_CUI_MM_MODS_CONTAINS",                                      "包含{1_total}个MOD ({2_enabled}/{1_total})"),
("zh_Hans_CN", "LOC_CUI_MM_MODS_BY",                                            "作者 '{1_author}' 的MOD"),
("zh_Hans_CN", "LOC_CUI_MM_UNNAMED_FOLDER",                                     "未命名的文件夹"),
("zh_Hans_CN", "LOC_CUI_MM_UPDATED_WEEK",                                       "更新日期：< 1周"),
("zh_Hans_CN", "LOC_CUI_MM_UPDATED_MONTH1",                                     "更新日期：< 1个月"),
("zh_Hans_CN", "LOC_CUI_MM_UPDATED_MONTH3",                                     "更新日期：< 3个月"),
("zh_Hans_CN", "LOC_CUI_MM_UPDATED_MONTH6",                                     "更新日期：< 6个月"),
("zh_Hans_CN", "LOC_CUI_MM_UPDATED_MORE",                                       "超过半年未更新"),
("zh_Hans_CN", "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "按作者整理"),
("zh_Hans_CN", "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "按更新日期整理"),
("zh_Hans_CN", "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "按启用情况整理"),
("zh_Hans_CN", "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "按自定义文件夹整理"),
("zh_Hans_CN", "LOC_CUI_MM_USER_GUIDE",                                         "使用指南"),
("zh_Hans_CN", "LOC_CUI_MM_GUIDE",                                              "模组[NEWLINE][ICON_BULLET] 左键：选择 / 取消选择[NEWLINE][ICON_BULLET] 右键：启用 / 禁用[NEWLINE][ICON_BULLET] 中键：关闭文件夹[NEWLINE][NEWLINE]文件夹[NEWLINE][ICON_BULLET] 左键：打开 / 关闭[NEWLINE][ICON_BULLET] 右键：全部启用 / 全部禁用[NEWLINE][NEWLINE][NEWLINE]自定义文件夹[NEWLINE][ICON_BULLET] 你可以在以下路径找到配置文件‘CustomFolder.lua’：[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] 你可以使用任意文本编辑器打开并修改它。[NEWLINE][ICON_BULLET] 然后根据文件里的说明来自定义你的文件夹。"),
("zh_Hans_CN", "LOC_CUI_MM_GENERATE_CODE",                                      "生成：Mod ID"),
("zh_Hans_CN", "LOC_CUI_MM_CODE_GUIDE",                                         "将以下代码添加到‘CustomFolder.lua’中[NEWLINE]以将此mod添加到自定义文件夹"),
("zh_Hans_CN", "LOC_CUI_MM_ENABLE_CONFIRM",                                     "启用确认"),
("zh_Hans_CN", "LOC_CUI_MM_ENABLE_DIALOG",                                      "该文件夹依赖于其他文件夹中的{1_num}个MOD。[NEWLINE]是否一并启用它们？"),
("zh_Hans_CN", "LOC_CUI_MM_DISABLE_CONFIRM",                                    "禁用确认"),
("zh_Hans_CN", "LOC_CUI_MM_DISABLE_DIALOG",                                     "其他文件夹中有{1_num}个MOD依赖于该文件夹。[NEWLINE]是否一并禁用它们？"),
("zh_Hans_CN", "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "非创意工坊"),
("zh_Hans_CN", "LOC_CUI_MM_NON_STEAM_MOD",                                      "这不是一个创意工坊MOD"),


-- =============================================================================
("zh_Hant_HK", "LOC_CUI_MM_MAP_CREATED",                                        "創建於：{1_Time: datetime}"),
("zh_Hant_HK", "LOC_CUI_MM_MODS_CONTAINS",                                      "包含{1_total}个MOD ({2_enabled}/{1_total})"),
("zh_Hant_HK", "LOC_CUI_MM_MODS_BY",                                            "作者 '{1_author}' 的MOD"),
("zh_Hant_HK", "LOC_CUI_MM_UNNAMED_FOLDER",                                     "未命名的文件夹"),
("zh_Hant_HK", "LOC_CUI_MM_UPDATED_WEEK",                                       "更新日期：< 1周"),
("zh_Hant_HK", "LOC_CUI_MM_UPDATED_MONTH1",                                     "更新日期：< 1个月"),
("zh_Hant_HK", "LOC_CUI_MM_UPDATED_MONTH3",                                     "更新日期：< 3个月"),
("zh_Hant_HK", "LOC_CUI_MM_UPDATED_MONTH6",                                     "更新日期：< 6个月"),
("zh_Hant_HK", "LOC_CUI_MM_UPDATED_MORE",                                       "超过半年未更新"),
("zh_Hant_HK", "LOC_CUI_MM_ORGANIZED_BY_AUTHOR",                                "按作者整理"),
("zh_Hant_HK", "LOC_CUI_MM_ORGANIZED_BY_DATE",                                  "按更新日期整理"),
("zh_Hant_HK", "LOC_CUI_MM_ORGANIZED_BY_ENABLED",                               "按启用情况整理"),
("zh_Hant_HK", "LOC_CUI_MM_ORGANIZED_BY_CUSTOM",                                "按自定义文件夹整理"),
("zh_Hant_HK", "LOC_CUI_MM_USER_GUIDE",                                         "使用指南"),
("zh_Hant_HK", "LOC_CUI_MM_GUIDE",                                              "模组[NEWLINE][ICON_BULLET] 左键：选择 / 取消选择[NEWLINE][ICON_BULLET] 右键：启用 / 禁用[NEWLINE][ICON_BULLET] 中键：关闭文件夹[NEWLINE][NEWLINE]文件夹[NEWLINE][ICON_BULLET] 左键：打开 / 关闭[NEWLINE][ICON_BULLET] 右键：全部启用 / 全部禁用[NEWLINE][NEWLINE][NEWLINE]自定义文件夹[NEWLINE][ICON_BULLET] 你可以在以下路径找到配置文件‘CustomFolder.lua’：[NEWLINE][ICON_BULLET] \Steam\steamapps\workshop\content\289070\1712085767[NEWLINE][ICON_BULLET] 你可以使用任意文本编辑器打开并修改它。[NEWLINE][ICON_BULLET] 然后根据文件里的说明来自定义你的文件夹。"),
("zh_Hant_HK", "LOC_CUI_MM_GENERATE_CODE",                                      "生成：Mod ID"),
("zh_Hant_HK", "LOC_CUI_MM_CODE_GUIDE",                                         "将以下代码添加到‘CustomFolder.lua’中[NEWLINE]以将此mod添加到自定义文件夹"),
("zh_Hant_HK", "LOC_CUI_MM_ENABLE_CONFIRM",                                     "启用确认"),
("zh_Hant_HK", "LOC_CUI_MM_ENABLE_DIALOG",                                      "该文件夹依赖于其他文件夹中的{1_num}个MOD。[NEWLINE]是否一并启用它们？"),
("zh_Hant_HK", "LOC_CUI_MM_DISABLE_CONFIRM",                                    "禁用确认"),
("zh_Hant_HK", "LOC_CUI_MM_DISABLE_DIALOG",                                     "其他文件夹中有{1_num}个MOD依赖于该文件夹。[NEWLINE]是否一并禁用它们？"),
("zh_Hant_HK", "LOC_CUI_MM_NON_STEAM_FOLDER",                                   "非创意工坊"),
("zh_Hant_HK", "LOC_CUI_MM_NON_STEAM_MOD",                                      "这不是一个创意工坊MOD"),


-- =============================================================================
("xx_XX", "LOC_CUI_COLON", ": ");
-- EOF